import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Use',
  description: 'Terms of use for MAX EV Business Lending.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-slate-200">
        <div className="max-w-3xl mx-auto px-6 h-14 flex items-center">
          <Link href="/" className="text-slate-500 hover:text-slate-900 text-sm transition-colors flex items-center gap-1.5">
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            MAX EV Business Lending
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-14">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Use</h1>
        <p className="text-slate-400 text-sm mb-10">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

        <div className="prose prose-slate max-w-none text-sm leading-relaxed space-y-8">

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-3">1. Acceptance</h2>
            <p className="text-slate-600">By accessing or using the MAX EV Business Lending platform, you agree to these Terms of Use. If you do not agree, do not use the platform.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-3">2. Not a Direct Lender</h2>
            <p className="text-slate-600">MAX EV Business Lending is a technology-based loan pre-qualification and lead routing service. We are not a direct lender, bank, or financial institution. We do not make lending decisions — we analyze applicant profiles using AI and route qualified applicants to third-party lending partners. Approval is subject to each partner's own underwriting criteria and is not guaranteed.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-3">3. Accuracy of Information</h2>
            <p className="text-slate-600">You agree to provide accurate, current, and complete information in your application. Providing false or misleading information may result in disqualification and could constitute fraud under applicable law. Our pre-qualification score is based on the self-reported data you provide and does not constitute a guaranteed offer of credit.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-3">4. AI-Generated Analysis</h2>
            <p className="text-slate-600">Underwriting scores and recommendations are generated by artificial intelligence and are intended as a pre-qualification estimate only. They do not represent a binding credit decision, commitment to lend, or guarantee of loan terms. All final lending decisions are made by the applicable lending partner.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-3">5. Electronic Communications</h2>
            <p className="text-slate-600">By submitting an application, you consent to receive electronic communications related to your application, including underwriting results, decision notices, and follow-up from lending partners or our team.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-3">6. Intellectual Property</h2>
            <p className="text-slate-600">All platform content, design, code, and AI models are the property of MAX EV Business Lending or its licensors. You may not copy, reverse engineer, or create derivative works without written permission.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-3">7. Limitation of Liability</h2>
            <p className="text-slate-600">TO THE MAXIMUM EXTENT PERMITTED BY LAW, MAX EV BUSINESS LENDING IS NOT LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE PLATFORM OR RELIANCE ON AI-GENERATED SCORES OR RECOMMENDATIONS. OUR TOTAL LIABILITY SHALL NOT EXCEED THE FEES PAID BY YOU TO US IN THE PRIOR 12 MONTHS, IF ANY.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-3">8. Prohibited Use</h2>
            <p className="text-slate-600">You may not use the platform to submit fraudulent applications, impersonate another business or individual, attempt to reverse-engineer our AI models, or engage in any activity that violates applicable law.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-3">9. Governing Law</h2>
            <p className="text-slate-600">These terms are governed by the laws of the State of Texas, without regard to conflict of law principles. Disputes shall be resolved in the courts of Dallas County, Texas.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-3">10. Changes</h2>
            <p className="text-slate-600">We reserve the right to update these terms at any time. Continued use after changes constitutes acceptance of the revised terms.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-900 mb-3">11. Contact</h2>
            <p className="text-slate-600">MAX EV Business Lending<br />
            Email: <a href="mailto:info@max-ev-holdings.com" className="text-emerald-600 hover:underline">info@max-ev-holdings.com</a>
            </p>
          </section>
        </div>
      </main>
    </div>
  )
}
